# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FirePick&trade;
email: jndetlefsen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  FirePick Delta is an open source 3-axis rotational delta factory robot.
  In the first version it will be used as a pick and place machine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
github_username:  jandetlefsen

# Build settings
markdown: kramdown

relative_permalinks: false

collections:
  faq:
    output: true
    permalink: /faq/:path/